### ISSUE TITLE
三年没更了，kangle除了彩虹没人维护了吗

### ISSUE THREAD

**Issue by Qicloud-W** [1265578519/kangle#12]
就这么落幕了么

**Comment by 1265578519** [comment]
ep停更，目前只持续维护更新kangle核心
![IMG_20241028_114123_271](https://github.com/user-attachments/assets/5a77b5fb-9c3a-4d22-bc94-f293f2709528)
核心相关可参考官方仓库
https://github.com/keengo99/kangle

新版kangle也还没定版下来，，还在开发阶段，感觉现在3.5的旧版本更好用，3.6新版改成动态加载库了，全部拆分模块化，3.5的二进制文件50MB，3.6变成1MB
