### ISSUE TITLE
error dump win7 64

### ISSUE THREAD

**Issue by 423230557** [1265578519/kangle#5]
![360 20180318084129342](https://user-images.githubusercontent.com/10486005/37561369-fe2b261e-2a87-11e8-95e8-8dc60bde805f.jpg)
kangle.exe_9952.dmp.zip
[kangle.exe_9952.zip](https://github.com/1265578519/kangle/files/1822218/kangle.exe_9952.zip)

**Comment by 423230557** [comment]
该线程尝试读写某个虚拟地址，而它对该地址不具有相应的访问权限

**Comment by 1265578519** [comment]
@423230557 and D:\kangle\var\server.log Report bugs to <keengo99@gmail.com>.
