### ISSUE TITLE
无法判断系统类型怎么回事？？？我用国产飞腾

### ISSUE THREAD

**Issue by dyfnino** [1265578519/kangle#8]
执行：./configure --prefix=/vhs/kangle --enable-disk-cache --enable-http2 --enable-ipv6 --enable-ssl --enable-vh-limit
报错：checking build system type... ./config.guess: unable to guess system type

请问怎么解决？

**Comment by 1265578519** [comment]
具体什么系统

**Comment by dyfnino** [comment]
> 具体什么系统
Kylin 国产麒麟系统，安装kangle的是无法 判断Kylin 只能判断是centos还Ubuntu

**Comment by dyfnino** [comment]
国产飞腾系统用的是 Kylin（麒麟）

**Comment by 1265578519** [comment]
这个问题你可能要问问官方人员了
